Repository Azure-Leap/Lucky-Paws, pull requests merged in 2023-05, with the labels that each got.

#62 Enerel
  be/app.ts
  be/controller/blog.ts
  be/controller/blogCategory.ts
  be/controller/products.ts
  be/controller/user.ts
  be/models/blog.ts
  be/models/blogCategories.ts
  be/models/products.ts
  be/models/user.ts
  be/routes/blog.ts
  be/routes/blogCategory.ts
  be/routes/user.ts
  fe/src/assets/images/blog.png
  fe/src/components/CategoryCards/CategoryCards.tsx
  fe/src/components/DogsCard/DogsCard.tsx
  fe/src/components/Footer/Footer.tsx
  fe/src/components/Navbar/Navbar.tsx
  fe/src/components/Shop/Shop.tsx
  fe/src/components/Shop/ShopCard.tsx
  fe/src/components/Story/Story.tsx
  fe/src/hooks/useBlogs.tsx
  fe/src/hooks/useProducts.tsx
  fe/src/pages/blog/[idx].tsx
  fe/src/pages/payment/index.tsx
  fe/src/pages/products/[id].tsx
  fe/src/pages/products/index.tsx
  fe/src/utils/interfaces/index.ts
Labels: Back-End

#63 Enerel
  be/app.ts
  be/controller/animal.ts
  be/controller/animalType.ts
  be/middlewares/upload.ts
  be/models/animal.ts
  be/models/animalType.ts
  be/models/blog.ts
  be/package-lock.json
  be/package.json
  be/routes/animal.ts
  be/routes/animalType.ts
  be/utils/cloudinary.ts
  fe/next.config.js
  fe/src/components/Navbar/Navbar.tsx
  fe/src/components/Shop/ShopCard.tsx
  fe/src/hooks/useBlogs.tsx
  fe/src/pages/blog/[id].tsx
  fe/src/pages/blog/[idx].tsx
  fe/src/pages/blog/index.tsx
  fe/src/pages/products/[id].tsx
  fe/src/pages/products/index.tsx
  fe/src/utils/interfaces/index.ts
Labels: component, page, Front-End, Back-End

#98 auth done
  be/controller/user.ts
  be/models/user.ts
  be/package-lock.json
  be/package.json
  be/routes/user.ts
  fe/package-lock.json
  fe/package.json
  fe/src/components/Login/SigninForm.tsx
  fe/src/components/Login/SignupForm.tsx
  fe/src/components/Navbar/Navbar.tsx
Labels: component, Front-End, Back-End

#103 auth done
  fe/package-lock.json
  fe/package.json
  fe/src/components/Login/SigninForm.tsx
  fe/src/components/Login/SignupForm.tsx
  fe/src/components/Navbar/Navbar.tsx
  fe/src/components/ProfileDropDown/ProfileDropDown.tsx
  fe/src/context/UserContext.tsx
  fe/src/pages/_app.tsx
  fe/src/utils/interfaces/index.ts
Labels: component, Front-End, Back-End

#104 profile
  be/controller/user.ts
  be/models/user.ts
  fe/next.config.js
  fe/src/components/Navbar/Navbar.tsx
  fe/src/components/ProfileDropDown/ProfileDropDown.tsx
  fe/src/context/UserContext.tsx
Labels: Front-End
